/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedLobSummaryRouteImport } from './routes/_authenticated/lob-summary'
import { Route as errors503RouteImport } from './routes/(errors)/503'
import { Route as errors500RouteImport } from './routes/(errors)/500'
import { Route as errors404RouteImport } from './routes/(errors)/404'
import { Route as errors403RouteImport } from './routes/(errors)/403'
import { Route as errors401RouteImport } from './routes/(errors)/401'
import { Route as authSignUpRouteImport } from './routes/(auth)/sign-up'
import { Route as authSignIn2RouteImport } from './routes/(auth)/sign-in-2'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as authOtpRouteImport } from './routes/(auth)/otp'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as AuthenticatedSettingsRouteRouteImport } from './routes/_authenticated/settings/route'
import { Route as AuthenticatedUsersIndexRouteImport } from './routes/_authenticated/users/index'
import { Route as AuthenticatedTasksIndexRouteImport } from './routes/_authenticated/tasks/index'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedPremiumsIndexRouteImport } from './routes/_authenticated/premiums/index'
import { Route as AuthenticatedPlansIndexRouteImport } from './routes/_authenticated/plans/index'
import { Route as AuthenticatedMembersIndexRouteImport } from './routes/_authenticated/members/index'
import { Route as AuthenticatedLineOfBusinessIndexRouteImport } from './routes/_authenticated/line-of-business/index'
import { Route as AuthenticatedHospitalsIndexRouteImport } from './routes/_authenticated/hospitals/index'
import { Route as AuthenticatedHelpCenterIndexRouteImport } from './routes/_authenticated/help-center/index'
import { Route as AuthenticatedClaimsIndexRouteImport } from './routes/_authenticated/claims/index'
import { Route as AuthenticatedChatsIndexRouteImport } from './routes/_authenticated/chats/index'
import { Route as AuthenticatedBranchesIndexRouteImport } from './routes/_authenticated/branches/index'
import { Route as AuthenticatedAuditLogsIndexRouteImport } from './routes/_authenticated/audit-logs/index'
import { Route as AuthenticatedAppsIndexRouteImport } from './routes/_authenticated/apps/index'
import { Route as AuthenticatedUsersNewRouteImport } from './routes/_authenticated/users/new'
import { Route as AuthenticatedUsersIdRouteImport } from './routes/_authenticated/users/$id'
import { Route as AuthenticatedSettingsSecurityRouteImport } from './routes/_authenticated/settings/security'
import { Route as AuthenticatedSettingsAppearanceRouteImport } from './routes/_authenticated/settings/appearance'
import { Route as AuthenticatedPremiumsIdRouteImport } from './routes/_authenticated/premiums/$id'
import { Route as AuthenticatedPlansNewRouteImport } from './routes/_authenticated/plans/new'
import { Route as AuthenticatedPlansIdRouteImport } from './routes/_authenticated/plans/$id'
import { Route as AuthenticatedMembersNewRouteImport } from './routes/_authenticated/members/new'
import { Route as AuthenticatedMembersIdRouteImport } from './routes/_authenticated/members/$id'
import { Route as AuthenticatedLineOfBusinessNewRouteImport } from './routes/_authenticated/line-of-business/new'
import { Route as AuthenticatedLineOfBusinessIdRouteImport } from './routes/_authenticated/line-of-business/$id'
import { Route as AuthenticatedHospitalsNewRouteImport } from './routes/_authenticated/hospitals/new'
import { Route as AuthenticatedHospitalsIdRouteImport } from './routes/_authenticated/hospitals/$id'
import { Route as AuthenticatedErrorsErrorRouteImport } from './routes/_authenticated/errors/$error'
import { Route as AuthenticatedClaimsIdRouteImport } from './routes/_authenticated/claims/$id'
import { Route as AuthenticatedBranchesNewRouteImport } from './routes/_authenticated/branches/new'
import { Route as AuthenticatedBranchesIdRouteImport } from './routes/_authenticated/branches/$id'
import { Route as AuthenticatedAuditLogsIdRouteImport } from './routes/_authenticated/audit-logs/$id'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLobSummaryRoute = AuthenticatedLobSummaryRouteImport.update({
  id: '/lob-summary',
  path: '/lob-summary',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const errors503Route = errors503RouteImport.update({
  id: '/(errors)/503',
  path: '/503',
  getParentRoute: () => rootRouteImport,
} as any)
const errors500Route = errors500RouteImport.update({
  id: '/(errors)/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const errors404Route = errors404RouteImport.update({
  id: '/(errors)/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const errors403Route = errors403RouteImport.update({
  id: '/(errors)/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const errors401Route = errors401RouteImport.update({
  id: '/(errors)/401',
  path: '/401',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignUpRoute = authSignUpRouteImport.update({
  id: '/(auth)/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignIn2Route = authSignIn2RouteImport.update({
  id: '/(auth)/sign-in-2',
  path: '/sign-in-2',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const authOtpRoute = authOtpRouteImport.update({
  id: '/(auth)/otp',
  path: '/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/(auth)/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRouteRoute =
  AuthenticatedSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedUsersIndexRoute = AuthenticatedUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTasksIndexRoute = AuthenticatedTasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedPremiumsIndexRoute =
  AuthenticatedPremiumsIndexRouteImport.update({
    id: '/premiums/',
    path: '/premiums/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPlansIndexRoute = AuthenticatedPlansIndexRouteImport.update({
  id: '/plans/',
  path: '/plans/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMembersIndexRoute =
  AuthenticatedMembersIndexRouteImport.update({
    id: '/members/',
    path: '/members/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLineOfBusinessIndexRoute =
  AuthenticatedLineOfBusinessIndexRouteImport.update({
    id: '/line-of-business/',
    path: '/line-of-business/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHospitalsIndexRoute =
  AuthenticatedHospitalsIndexRouteImport.update({
    id: '/hospitals/',
    path: '/hospitals/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHelpCenterIndexRoute =
  AuthenticatedHelpCenterIndexRouteImport.update({
    id: '/help-center/',
    path: '/help-center/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClaimsIndexRoute =
  AuthenticatedClaimsIndexRouteImport.update({
    id: '/claims/',
    path: '/claims/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedChatsIndexRoute = AuthenticatedChatsIndexRouteImport.update({
  id: '/chats/',
  path: '/chats/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBranchesIndexRoute =
  AuthenticatedBranchesIndexRouteImport.update({
    id: '/branches/',
    path: '/branches/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAuditLogsIndexRoute =
  AuthenticatedAuditLogsIndexRouteImport.update({
    id: '/audit-logs/',
    path: '/audit-logs/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppsIndexRoute = AuthenticatedAppsIndexRouteImport.update({
  id: '/apps/',
  path: '/apps/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedUsersNewRoute = AuthenticatedUsersNewRouteImport.update({
  id: '/users/new',
  path: '/users/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedUsersIdRoute = AuthenticatedUsersIdRouteImport.update({
  id: '/users/$id',
  path: '/users/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsSecurityRoute =
  AuthenticatedSettingsSecurityRouteImport.update({
    id: '/security',
    path: '/security',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAppearanceRoute =
  AuthenticatedSettingsAppearanceRouteImport.update({
    id: '/appearance',
    path: '/appearance',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedPremiumsIdRoute = AuthenticatedPremiumsIdRouteImport.update({
  id: '/premiums/$id',
  path: '/premiums/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPlansNewRoute = AuthenticatedPlansNewRouteImport.update({
  id: '/plans/new',
  path: '/plans/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPlansIdRoute = AuthenticatedPlansIdRouteImport.update({
  id: '/plans/$id',
  path: '/plans/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMembersNewRoute = AuthenticatedMembersNewRouteImport.update({
  id: '/members/new',
  path: '/members/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMembersIdRoute = AuthenticatedMembersIdRouteImport.update({
  id: '/members/$id',
  path: '/members/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLineOfBusinessNewRoute =
  AuthenticatedLineOfBusinessNewRouteImport.update({
    id: '/line-of-business/new',
    path: '/line-of-business/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLineOfBusinessIdRoute =
  AuthenticatedLineOfBusinessIdRouteImport.update({
    id: '/line-of-business/$id',
    path: '/line-of-business/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHospitalsNewRoute =
  AuthenticatedHospitalsNewRouteImport.update({
    id: '/hospitals/new',
    path: '/hospitals/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHospitalsIdRoute =
  AuthenticatedHospitalsIdRouteImport.update({
    id: '/hospitals/$id',
    path: '/hospitals/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedErrorsErrorRoute =
  AuthenticatedErrorsErrorRouteImport.update({
    id: '/errors/$error',
    path: '/errors/$error',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClaimsIdRoute = AuthenticatedClaimsIdRouteImport.update({
  id: '/claims/$id',
  path: '/claims/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBranchesNewRoute =
  AuthenticatedBranchesNewRouteImport.update({
    id: '/branches/new',
    path: '/branches/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBranchesIdRoute = AuthenticatedBranchesIdRouteImport.update({
  id: '/branches/$id',
  path: '/branches/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAuditLogsIdRoute =
  AuthenticatedAuditLogsIdRouteImport.update({
    id: '/audit-logs/$id',
    path: '/audit-logs/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/sign-in-2': typeof authSignIn2Route
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/lob-summary': typeof AuthenticatedLobSummaryRoute
  '/audit-logs/$id': typeof AuthenticatedAuditLogsIdRoute
  '/branches/$id': typeof AuthenticatedBranchesIdRoute
  '/branches/new': typeof AuthenticatedBranchesNewRoute
  '/claims/$id': typeof AuthenticatedClaimsIdRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/hospitals/$id': typeof AuthenticatedHospitalsIdRoute
  '/hospitals/new': typeof AuthenticatedHospitalsNewRoute
  '/line-of-business/$id': typeof AuthenticatedLineOfBusinessIdRoute
  '/line-of-business/new': typeof AuthenticatedLineOfBusinessNewRoute
  '/members/$id': typeof AuthenticatedMembersIdRoute
  '/members/new': typeof AuthenticatedMembersNewRoute
  '/plans/$id': typeof AuthenticatedPlansIdRoute
  '/plans/new': typeof AuthenticatedPlansNewRoute
  '/premiums/$id': typeof AuthenticatedPremiumsIdRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/security': typeof AuthenticatedSettingsSecurityRoute
  '/users/$id': typeof AuthenticatedUsersIdRoute
  '/users/new': typeof AuthenticatedUsersNewRoute
  '/apps/': typeof AuthenticatedAppsIndexRoute
  '/audit-logs/': typeof AuthenticatedAuditLogsIndexRoute
  '/branches/': typeof AuthenticatedBranchesIndexRoute
  '/chats/': typeof AuthenticatedChatsIndexRoute
  '/claims/': typeof AuthenticatedClaimsIndexRoute
  '/help-center/': typeof AuthenticatedHelpCenterIndexRoute
  '/hospitals/': typeof AuthenticatedHospitalsIndexRoute
  '/line-of-business/': typeof AuthenticatedLineOfBusinessIndexRoute
  '/members/': typeof AuthenticatedMembersIndexRoute
  '/plans/': typeof AuthenticatedPlansIndexRoute
  '/premiums/': typeof AuthenticatedPremiumsIndexRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/tasks/': typeof AuthenticatedTasksIndexRoute
  '/users/': typeof AuthenticatedUsersIndexRoute
}
export interface FileRoutesByTo {
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/sign-in-2': typeof authSignIn2Route
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/lob-summary': typeof AuthenticatedLobSummaryRoute
  '/': typeof AuthenticatedIndexRoute
  '/audit-logs/$id': typeof AuthenticatedAuditLogsIdRoute
  '/branches/$id': typeof AuthenticatedBranchesIdRoute
  '/branches/new': typeof AuthenticatedBranchesNewRoute
  '/claims/$id': typeof AuthenticatedClaimsIdRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/hospitals/$id': typeof AuthenticatedHospitalsIdRoute
  '/hospitals/new': typeof AuthenticatedHospitalsNewRoute
  '/line-of-business/$id': typeof AuthenticatedLineOfBusinessIdRoute
  '/line-of-business/new': typeof AuthenticatedLineOfBusinessNewRoute
  '/members/$id': typeof AuthenticatedMembersIdRoute
  '/members/new': typeof AuthenticatedMembersNewRoute
  '/plans/$id': typeof AuthenticatedPlansIdRoute
  '/plans/new': typeof AuthenticatedPlansNewRoute
  '/premiums/$id': typeof AuthenticatedPremiumsIdRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/security': typeof AuthenticatedSettingsSecurityRoute
  '/users/$id': typeof AuthenticatedUsersIdRoute
  '/users/new': typeof AuthenticatedUsersNewRoute
  '/apps': typeof AuthenticatedAppsIndexRoute
  '/audit-logs': typeof AuthenticatedAuditLogsIndexRoute
  '/branches': typeof AuthenticatedBranchesIndexRoute
  '/chats': typeof AuthenticatedChatsIndexRoute
  '/claims': typeof AuthenticatedClaimsIndexRoute
  '/help-center': typeof AuthenticatedHelpCenterIndexRoute
  '/hospitals': typeof AuthenticatedHospitalsIndexRoute
  '/line-of-business': typeof AuthenticatedLineOfBusinessIndexRoute
  '/members': typeof AuthenticatedMembersIndexRoute
  '/plans': typeof AuthenticatedPlansIndexRoute
  '/premiums': typeof AuthenticatedPremiumsIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/tasks': typeof AuthenticatedTasksIndexRoute
  '/users': typeof AuthenticatedUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/otp': typeof authOtpRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/(auth)/sign-in-2': typeof authSignIn2Route
  '/(auth)/sign-up': typeof authSignUpRoute
  '/(errors)/401': typeof errors401Route
  '/(errors)/403': typeof errors403Route
  '/(errors)/404': typeof errors404Route
  '/(errors)/500': typeof errors500Route
  '/(errors)/503': typeof errors503Route
  '/_authenticated/lob-summary': typeof AuthenticatedLobSummaryRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/audit-logs/$id': typeof AuthenticatedAuditLogsIdRoute
  '/_authenticated/branches/$id': typeof AuthenticatedBranchesIdRoute
  '/_authenticated/branches/new': typeof AuthenticatedBranchesNewRoute
  '/_authenticated/claims/$id': typeof AuthenticatedClaimsIdRoute
  '/_authenticated/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/_authenticated/hospitals/$id': typeof AuthenticatedHospitalsIdRoute
  '/_authenticated/hospitals/new': typeof AuthenticatedHospitalsNewRoute
  '/_authenticated/line-of-business/$id': typeof AuthenticatedLineOfBusinessIdRoute
  '/_authenticated/line-of-business/new': typeof AuthenticatedLineOfBusinessNewRoute
  '/_authenticated/members/$id': typeof AuthenticatedMembersIdRoute
  '/_authenticated/members/new': typeof AuthenticatedMembersNewRoute
  '/_authenticated/plans/$id': typeof AuthenticatedPlansIdRoute
  '/_authenticated/plans/new': typeof AuthenticatedPlansNewRoute
  '/_authenticated/premiums/$id': typeof AuthenticatedPremiumsIdRoute
  '/_authenticated/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/_authenticated/settings/security': typeof AuthenticatedSettingsSecurityRoute
  '/_authenticated/users/$id': typeof AuthenticatedUsersIdRoute
  '/_authenticated/users/new': typeof AuthenticatedUsersNewRoute
  '/_authenticated/apps/': typeof AuthenticatedAppsIndexRoute
  '/_authenticated/audit-logs/': typeof AuthenticatedAuditLogsIndexRoute
  '/_authenticated/branches/': typeof AuthenticatedBranchesIndexRoute
  '/_authenticated/chats/': typeof AuthenticatedChatsIndexRoute
  '/_authenticated/claims/': typeof AuthenticatedClaimsIndexRoute
  '/_authenticated/help-center/': typeof AuthenticatedHelpCenterIndexRoute
  '/_authenticated/hospitals/': typeof AuthenticatedHospitalsIndexRoute
  '/_authenticated/line-of-business/': typeof AuthenticatedLineOfBusinessIndexRoute
  '/_authenticated/members/': typeof AuthenticatedMembersIndexRoute
  '/_authenticated/plans/': typeof AuthenticatedPlansIndexRoute
  '/_authenticated/premiums/': typeof AuthenticatedPremiumsIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/tasks/': typeof AuthenticatedTasksIndexRoute
  '/_authenticated/users/': typeof AuthenticatedUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/forgot-password'
    | '/otp'
    | '/sign-in'
    | '/sign-in-2'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/lob-summary'
    | '/audit-logs/$id'
    | '/branches/$id'
    | '/branches/new'
    | '/claims/$id'
    | '/errors/$error'
    | '/hospitals/$id'
    | '/hospitals/new'
    | '/line-of-business/$id'
    | '/line-of-business/new'
    | '/members/$id'
    | '/members/new'
    | '/plans/$id'
    | '/plans/new'
    | '/premiums/$id'
    | '/settings/appearance'
    | '/settings/security'
    | '/users/$id'
    | '/users/new'
    | '/apps/'
    | '/audit-logs/'
    | '/branches/'
    | '/chats/'
    | '/claims/'
    | '/help-center/'
    | '/hospitals/'
    | '/line-of-business/'
    | '/members/'
    | '/plans/'
    | '/premiums/'
    | '/settings/'
    | '/tasks/'
    | '/users/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/forgot-password'
    | '/otp'
    | '/sign-in'
    | '/sign-in-2'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/lob-summary'
    | '/'
    | '/audit-logs/$id'
    | '/branches/$id'
    | '/branches/new'
    | '/claims/$id'
    | '/errors/$error'
    | '/hospitals/$id'
    | '/hospitals/new'
    | '/line-of-business/$id'
    | '/line-of-business/new'
    | '/members/$id'
    | '/members/new'
    | '/plans/$id'
    | '/plans/new'
    | '/premiums/$id'
    | '/settings/appearance'
    | '/settings/security'
    | '/users/$id'
    | '/users/new'
    | '/apps'
    | '/audit-logs'
    | '/branches'
    | '/chats'
    | '/claims'
    | '/help-center'
    | '/hospitals'
    | '/line-of-business'
    | '/members'
    | '/plans'
    | '/premiums'
    | '/settings'
    | '/tasks'
    | '/users'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_authenticated/settings'
    | '/(auth)/forgot-password'
    | '/(auth)/otp'
    | '/(auth)/sign-in'
    | '/(auth)/sign-in-2'
    | '/(auth)/sign-up'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/_authenticated/lob-summary'
    | '/_authenticated/'
    | '/_authenticated/audit-logs/$id'
    | '/_authenticated/branches/$id'
    | '/_authenticated/branches/new'
    | '/_authenticated/claims/$id'
    | '/_authenticated/errors/$error'
    | '/_authenticated/hospitals/$id'
    | '/_authenticated/hospitals/new'
    | '/_authenticated/line-of-business/$id'
    | '/_authenticated/line-of-business/new'
    | '/_authenticated/members/$id'
    | '/_authenticated/members/new'
    | '/_authenticated/plans/$id'
    | '/_authenticated/plans/new'
    | '/_authenticated/premiums/$id'
    | '/_authenticated/settings/appearance'
    | '/_authenticated/settings/security'
    | '/_authenticated/users/$id'
    | '/_authenticated/users/new'
    | '/_authenticated/apps/'
    | '/_authenticated/audit-logs/'
    | '/_authenticated/branches/'
    | '/_authenticated/chats/'
    | '/_authenticated/claims/'
    | '/_authenticated/help-center/'
    | '/_authenticated/hospitals/'
    | '/_authenticated/line-of-business/'
    | '/_authenticated/members/'
    | '/_authenticated/plans/'
    | '/_authenticated/premiums/'
    | '/_authenticated/settings/'
    | '/_authenticated/tasks/'
    | '/_authenticated/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authOtpRoute: typeof authOtpRoute
  authSignInRoute: typeof authSignInRoute
  authSignIn2Route: typeof authSignIn2Route
  authSignUpRoute: typeof authSignUpRoute
  errors401Route: typeof errors401Route
  errors403Route: typeof errors403Route
  errors404Route: typeof errors404Route
  errors500Route: typeof errors500Route
  errors503Route: typeof errors503Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/lob-summary': {
      id: '/_authenticated/lob-summary'
      path: '/lob-summary'
      fullPath: '/lob-summary'
      preLoaderRoute: typeof AuthenticatedLobSummaryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in-2': {
      id: '/(auth)/sign-in-2'
      path: '/sign-in-2'
      fullPath: '/sign-in-2'
      preLoaderRoute: typeof authSignIn2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/otp': {
      id: '/(auth)/otp'
      path: '/otp'
      fullPath: '/otp'
      preLoaderRoute: typeof authOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/users/': {
      id: '/_authenticated/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof AuthenticatedUsersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tasks/': {
      id: '/_authenticated/tasks/'
      path: '/tasks'
      fullPath: '/tasks/'
      preLoaderRoute: typeof AuthenticatedTasksIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/premiums/': {
      id: '/_authenticated/premiums/'
      path: '/premiums'
      fullPath: '/premiums/'
      preLoaderRoute: typeof AuthenticatedPremiumsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/plans/': {
      id: '/_authenticated/plans/'
      path: '/plans'
      fullPath: '/plans/'
      preLoaderRoute: typeof AuthenticatedPlansIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/members/': {
      id: '/_authenticated/members/'
      path: '/members'
      fullPath: '/members/'
      preLoaderRoute: typeof AuthenticatedMembersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/line-of-business/': {
      id: '/_authenticated/line-of-business/'
      path: '/line-of-business'
      fullPath: '/line-of-business/'
      preLoaderRoute: typeof AuthenticatedLineOfBusinessIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/hospitals/': {
      id: '/_authenticated/hospitals/'
      path: '/hospitals'
      fullPath: '/hospitals/'
      preLoaderRoute: typeof AuthenticatedHospitalsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/help-center/': {
      id: '/_authenticated/help-center/'
      path: '/help-center'
      fullPath: '/help-center/'
      preLoaderRoute: typeof AuthenticatedHelpCenterIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/claims/': {
      id: '/_authenticated/claims/'
      path: '/claims'
      fullPath: '/claims/'
      preLoaderRoute: typeof AuthenticatedClaimsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chats/': {
      id: '/_authenticated/chats/'
      path: '/chats'
      fullPath: '/chats/'
      preLoaderRoute: typeof AuthenticatedChatsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/branches/': {
      id: '/_authenticated/branches/'
      path: '/branches'
      fullPath: '/branches/'
      preLoaderRoute: typeof AuthenticatedBranchesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/audit-logs/': {
      id: '/_authenticated/audit-logs/'
      path: '/audit-logs'
      fullPath: '/audit-logs/'
      preLoaderRoute: typeof AuthenticatedAuditLogsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/apps/': {
      id: '/_authenticated/apps/'
      path: '/apps'
      fullPath: '/apps/'
      preLoaderRoute: typeof AuthenticatedAppsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/users/new': {
      id: '/_authenticated/users/new'
      path: '/users/new'
      fullPath: '/users/new'
      preLoaderRoute: typeof AuthenticatedUsersNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/users/$id': {
      id: '/_authenticated/users/$id'
      path: '/users/$id'
      fullPath: '/users/$id'
      preLoaderRoute: typeof AuthenticatedUsersIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/security': {
      id: '/_authenticated/settings/security'
      path: '/security'
      fullPath: '/settings/security'
      preLoaderRoute: typeof AuthenticatedSettingsSecurityRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/appearance': {
      id: '/_authenticated/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof AuthenticatedSettingsAppearanceRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/premiums/$id': {
      id: '/_authenticated/premiums/$id'
      path: '/premiums/$id'
      fullPath: '/premiums/$id'
      preLoaderRoute: typeof AuthenticatedPremiumsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/plans/new': {
      id: '/_authenticated/plans/new'
      path: '/plans/new'
      fullPath: '/plans/new'
      preLoaderRoute: typeof AuthenticatedPlansNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/plans/$id': {
      id: '/_authenticated/plans/$id'
      path: '/plans/$id'
      fullPath: '/plans/$id'
      preLoaderRoute: typeof AuthenticatedPlansIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/members/new': {
      id: '/_authenticated/members/new'
      path: '/members/new'
      fullPath: '/members/new'
      preLoaderRoute: typeof AuthenticatedMembersNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/members/$id': {
      id: '/_authenticated/members/$id'
      path: '/members/$id'
      fullPath: '/members/$id'
      preLoaderRoute: typeof AuthenticatedMembersIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/line-of-business/new': {
      id: '/_authenticated/line-of-business/new'
      path: '/line-of-business/new'
      fullPath: '/line-of-business/new'
      preLoaderRoute: typeof AuthenticatedLineOfBusinessNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/line-of-business/$id': {
      id: '/_authenticated/line-of-business/$id'
      path: '/line-of-business/$id'
      fullPath: '/line-of-business/$id'
      preLoaderRoute: typeof AuthenticatedLineOfBusinessIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/hospitals/new': {
      id: '/_authenticated/hospitals/new'
      path: '/hospitals/new'
      fullPath: '/hospitals/new'
      preLoaderRoute: typeof AuthenticatedHospitalsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/hospitals/$id': {
      id: '/_authenticated/hospitals/$id'
      path: '/hospitals/$id'
      fullPath: '/hospitals/$id'
      preLoaderRoute: typeof AuthenticatedHospitalsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/errors/$error': {
      id: '/_authenticated/errors/$error'
      path: '/errors/$error'
      fullPath: '/errors/$error'
      preLoaderRoute: typeof AuthenticatedErrorsErrorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/claims/$id': {
      id: '/_authenticated/claims/$id'
      path: '/claims/$id'
      fullPath: '/claims/$id'
      preLoaderRoute: typeof AuthenticatedClaimsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/branches/new': {
      id: '/_authenticated/branches/new'
      path: '/branches/new'
      fullPath: '/branches/new'
      preLoaderRoute: typeof AuthenticatedBranchesNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/branches/$id': {
      id: '/_authenticated/branches/$id'
      path: '/branches/$id'
      fullPath: '/branches/$id'
      preLoaderRoute: typeof AuthenticatedBranchesIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/audit-logs/$id': {
      id: '/_authenticated/audit-logs/$id'
      path: '/audit-logs/$id'
      fullPath: '/audit-logs/$id'
      preLoaderRoute: typeof AuthenticatedAuditLogsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedSettingsRouteRouteChildren {
  AuthenticatedSettingsAppearanceRoute: typeof AuthenticatedSettingsAppearanceRoute
  AuthenticatedSettingsSecurityRoute: typeof AuthenticatedSettingsSecurityRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
}

const AuthenticatedSettingsRouteRouteChildren: AuthenticatedSettingsRouteRouteChildren =
  {
    AuthenticatedSettingsAppearanceRoute: AuthenticatedSettingsAppearanceRoute,
    AuthenticatedSettingsSecurityRoute: AuthenticatedSettingsSecurityRoute,
    AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
  }

const AuthenticatedSettingsRouteRouteWithChildren =
  AuthenticatedSettingsRouteRoute._addFileChildren(
    AuthenticatedSettingsRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedSettingsRouteRoute: typeof AuthenticatedSettingsRouteRouteWithChildren
  AuthenticatedLobSummaryRoute: typeof AuthenticatedLobSummaryRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedAuditLogsIdRoute: typeof AuthenticatedAuditLogsIdRoute
  AuthenticatedBranchesIdRoute: typeof AuthenticatedBranchesIdRoute
  AuthenticatedBranchesNewRoute: typeof AuthenticatedBranchesNewRoute
  AuthenticatedClaimsIdRoute: typeof AuthenticatedClaimsIdRoute
  AuthenticatedErrorsErrorRoute: typeof AuthenticatedErrorsErrorRoute
  AuthenticatedHospitalsIdRoute: typeof AuthenticatedHospitalsIdRoute
  AuthenticatedHospitalsNewRoute: typeof AuthenticatedHospitalsNewRoute
  AuthenticatedLineOfBusinessIdRoute: typeof AuthenticatedLineOfBusinessIdRoute
  AuthenticatedLineOfBusinessNewRoute: typeof AuthenticatedLineOfBusinessNewRoute
  AuthenticatedMembersIdRoute: typeof AuthenticatedMembersIdRoute
  AuthenticatedMembersNewRoute: typeof AuthenticatedMembersNewRoute
  AuthenticatedPlansIdRoute: typeof AuthenticatedPlansIdRoute
  AuthenticatedPlansNewRoute: typeof AuthenticatedPlansNewRoute
  AuthenticatedPremiumsIdRoute: typeof AuthenticatedPremiumsIdRoute
  AuthenticatedUsersIdRoute: typeof AuthenticatedUsersIdRoute
  AuthenticatedUsersNewRoute: typeof AuthenticatedUsersNewRoute
  AuthenticatedAppsIndexRoute: typeof AuthenticatedAppsIndexRoute
  AuthenticatedAuditLogsIndexRoute: typeof AuthenticatedAuditLogsIndexRoute
  AuthenticatedBranchesIndexRoute: typeof AuthenticatedBranchesIndexRoute
  AuthenticatedChatsIndexRoute: typeof AuthenticatedChatsIndexRoute
  AuthenticatedClaimsIndexRoute: typeof AuthenticatedClaimsIndexRoute
  AuthenticatedHelpCenterIndexRoute: typeof AuthenticatedHelpCenterIndexRoute
  AuthenticatedHospitalsIndexRoute: typeof AuthenticatedHospitalsIndexRoute
  AuthenticatedLineOfBusinessIndexRoute: typeof AuthenticatedLineOfBusinessIndexRoute
  AuthenticatedMembersIndexRoute: typeof AuthenticatedMembersIndexRoute
  AuthenticatedPlansIndexRoute: typeof AuthenticatedPlansIndexRoute
  AuthenticatedPremiumsIndexRoute: typeof AuthenticatedPremiumsIndexRoute
  AuthenticatedTasksIndexRoute: typeof AuthenticatedTasksIndexRoute
  AuthenticatedUsersIndexRoute: typeof AuthenticatedUsersIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedSettingsRouteRoute: AuthenticatedSettingsRouteRouteWithChildren,
  AuthenticatedLobSummaryRoute: AuthenticatedLobSummaryRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedAuditLogsIdRoute: AuthenticatedAuditLogsIdRoute,
  AuthenticatedBranchesIdRoute: AuthenticatedBranchesIdRoute,
  AuthenticatedBranchesNewRoute: AuthenticatedBranchesNewRoute,
  AuthenticatedClaimsIdRoute: AuthenticatedClaimsIdRoute,
  AuthenticatedErrorsErrorRoute: AuthenticatedErrorsErrorRoute,
  AuthenticatedHospitalsIdRoute: AuthenticatedHospitalsIdRoute,
  AuthenticatedHospitalsNewRoute: AuthenticatedHospitalsNewRoute,
  AuthenticatedLineOfBusinessIdRoute: AuthenticatedLineOfBusinessIdRoute,
  AuthenticatedLineOfBusinessNewRoute: AuthenticatedLineOfBusinessNewRoute,
  AuthenticatedMembersIdRoute: AuthenticatedMembersIdRoute,
  AuthenticatedMembersNewRoute: AuthenticatedMembersNewRoute,
  AuthenticatedPlansIdRoute: AuthenticatedPlansIdRoute,
  AuthenticatedPlansNewRoute: AuthenticatedPlansNewRoute,
  AuthenticatedPremiumsIdRoute: AuthenticatedPremiumsIdRoute,
  AuthenticatedUsersIdRoute: AuthenticatedUsersIdRoute,
  AuthenticatedUsersNewRoute: AuthenticatedUsersNewRoute,
  AuthenticatedAppsIndexRoute: AuthenticatedAppsIndexRoute,
  AuthenticatedAuditLogsIndexRoute: AuthenticatedAuditLogsIndexRoute,
  AuthenticatedBranchesIndexRoute: AuthenticatedBranchesIndexRoute,
  AuthenticatedChatsIndexRoute: AuthenticatedChatsIndexRoute,
  AuthenticatedClaimsIndexRoute: AuthenticatedClaimsIndexRoute,
  AuthenticatedHelpCenterIndexRoute: AuthenticatedHelpCenterIndexRoute,
  AuthenticatedHospitalsIndexRoute: AuthenticatedHospitalsIndexRoute,
  AuthenticatedLineOfBusinessIndexRoute: AuthenticatedLineOfBusinessIndexRoute,
  AuthenticatedMembersIndexRoute: AuthenticatedMembersIndexRoute,
  AuthenticatedPlansIndexRoute: AuthenticatedPlansIndexRoute,
  AuthenticatedPremiumsIndexRoute: AuthenticatedPremiumsIndexRoute,
  AuthenticatedTasksIndexRoute: AuthenticatedTasksIndexRoute,
  AuthenticatedUsersIndexRoute: AuthenticatedUsersIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  authForgotPasswordRoute: authForgotPasswordRoute,
  authOtpRoute: authOtpRoute,
  authSignInRoute: authSignInRoute,
  authSignIn2Route: authSignIn2Route,
  authSignUpRoute: authSignUpRoute,
  errors401Route: errors401Route,
  errors403Route: errors403Route,
  errors404Route: errors404Route,
  errors500Route: errors500Route,
  errors503Route: errors503Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
