name: CI

on:
  push:
    branches:
      - master
    paths-ignore:
      - 'docs/**'
      - '*.md'
  pull_request:
    paths-ignore:
      - 'docs/**'
      - '*.md'

jobs:
  test:
    name: Lint and typecheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Setup node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'

      - name: Enable pnpm
        run: npm i -g corepack@latest && corepack enable pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm nx run-many -t lint typecheck
